name: crick11
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter  
  bloc : ^8.1.2
  flutter_bloc : ^8.1.3
  equatable : ^2.0.5
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.7
  pin_code_fields: ^7.3.0
  intl_phone_field: ^3.1.0
  intl: 
  outline_gradient_button: ^2.0.0+1
  dotted_border: 2.0.0+3
  percent_indicator: ^4.2.3
  pie_chart: ^5.3.2
  easy_stepper: ^0.6.0 
  responsive_builder: 
  adaptive_theme :  ^3.2.1
  device_preview: ^1.1.0
  flutter_lints: ^2.0.1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterExtraBold.ttf
          weight: 800
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterBlack.ttf
          weight: 900
    - family: Sansation
      fonts: 
        - asset: assets/fonts/SansationBold.ttf
          weight: 700
        - asset: assets/fonts/SansationBoldItalic.ttf
          weight: 700
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanExtraBold.ttf
          weight: 800
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRomanBlack.ttf
          weight: 900
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400

